export default [
  {
    _id: "1",
    familia: "Abduhalimov",
    ism: "Muhammadaziz",
    ochestvo: "Muxiddinovich",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "2",
    familia: "Abduholiqov",
    ism: "Sanjarbek",
    ochestvo: "Muzaffar O`G`Li",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "3",
    familia: "Abdujalalov",
    ism: "Abdulloh",
    ochestvo: "Muzaffar o`g`li",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "4",
    familia: "Abdullayeva",
    ism: "Dilrabo",
    ochestvo: "Djamaliddinovna",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "5",
    familia: "Abdusamadova",
    ism: "Dinora",
    ochestvo: "Abdulazizovna",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "6",
    familia: "Abdusamadova",
    ism: "Munisaxon",
    ochestvo: "Anvarjon Qizi",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "7",
    familia: "Akilova",
    ism: "Nodira",
    ochestvo: "Shuxrat qizi",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "8",
    familia: "Alimdjanova",
    ism: "Saodat",
    ochestvo: "Xayrullayevna",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "9",
    familia: "Aripova",
    ism: "Nargiza",
    ochestvo: "Anvarovna",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "10",
    familia: "Asamova",
    ism: "Durdona",
    ochestvo: "Nu`Manjanovna",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
];
