export default [
  {
    _id: "1",
    familia: "Abduartikova",
    ism: "Rayyonabonu",
    ochestvo: "Baxtiyor qizi",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "2",
    familia: "Abduartikova",
    ism: "Samiyabegim",
    ochestvo: "Baxtiyor qizi",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "3",
    familia: "Abduqodirova",
    ism: "Dilbar",
    ochestvo: "Abdushukur Qizi",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "4",
    familia: "Abduraximov",
    ism: "Bekmirza",
    ochestvo: "Sardor oʻgʻli",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "5",
    familia: "Abdusaitova",
    ism: "Durdona",
    ochestvo: "Jamshid qizi",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "6",
    familia: "Abduxoliqova",
    ism: "Charos",
    ochestvo: "Umurzoq qizi",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "7",
    familia: "Abdushukurov",
    ism: "Xafizulloh",
    ochestvo: "Jamshid o'g'li",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "8",
    familia: "Abdushukurova",
    ism: "Sevara",
    ochestvo: "G'ayrat Qizi",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "9",
    familia: "Ablazova",
    ism: "Jamila",
    ochestvo: "Salayydinovna",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "10",
    familia: "Adiljonova",
    ism: "Maftuna",
    ochestvo: "Olim qizi",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
];
