export default [
  {
    _id: "1",
    familia: "Abbosxonova",
    ism: "Ozodaxon",
    ochestvo: "Ravshan o`g`li",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "2",
    familia: "Abdaliyeva",
    ism: "E'zoza",
    ochestvo: "Ziyodullayevnan",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "3",
    familia: "Abdaliyeva",
    ism: "Zarnigor",
    ochestvo: "Yo'zilmagan",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "4",
    familia: "Abdimo`minov",
    ism: "Saida'zim",
    ochestvo: "Sherzod o`g`li",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "5",
    familia: "Abdug`ofurov",
    ism: "Abdilbosit",
    ochestvo: "Doniyor o`g`li",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "6",
    familia: "Abduhalilova",
    ism: "E'zoza",
    ochestvo: "Baxrom qizi",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "7",
    familia: "Abdujabborova",
    ism: "E'zoza",
    ochestvo: "To`lqin qizi",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "8",
    familia: "Abdullayeva",
    ism: "Iroda",
    ochestvo: "Jasurbek qizi",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "9",
    familia: "Abduraxmonova",
    ism: "Osiyo",
    ochestvo: "Zoxidjon qizi",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "10",
    familia: "Abduzohidov",
    ism: "Kamronbek",
    ochestvo: "Botir o`g`li",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
];
