export default [
  {
    _id: "1",
    familia: "Abduhamidov",
    ism: "Diyorbek",
    ochestvo: "Sherzod o'g'li",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "2",
    familia: "Abdujalilova",
    ism: "Robiyaxon",
    ochestvo: "Toxirjon qizi",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "3",
    familia: "Abdulazizov",
    ism: "Abubakr",
    ochestvo: "Abduqodir o`g`li",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "4",
    familia: "Abdullayeva",
    ism: "E'zoza",
    ochestvo: "Dilshod qizi",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "5",
    familia: "Abdullayeva",
    ism: "Nilufar",
    ochestvo: "Yo'zilmagan",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "6",
    familia: "Abdullayeva",
    ism: "Shoxida",
    ochestvo: "Axmedovna",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "7",
    familia: "Abduraimova",
    ism: "Azizaxon",
    ochestvo: "Asqar qizi",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "8",
    familia: "Abduraxmanova",
    ism: "Ummukulsum",
    ochestvo: "Avaz qizi",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "9",
    familia: "Abduxoliqov",
    ism: "Shaxobiddin",
    ochestvo: "Abdumannon",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "10",
    familia: "Abzalova",
    ism: "Zaytuna",
    ochestvo: "Sagʻdullayevna",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
];
