export default [
  {
    _id: "1",
    familia: "Абидова",
    ism: "Дилафруз",
    ochestvo: "Нигматуллевна",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "2",
    familia: "Адилова",
    ism: "Жамиля",
    ochestvo: "Жасуровна",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "3",
    familia: "Азимова",
    ism: "Озодаx",
    ochestvo: "Кахрамон Кизи",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "4",
    familia: "Ан",
    ism: "E'zozaНина",
    ochestvo: "Валерьевна",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "5",
    familia: "Асадуллаева",
    ism: "Сайера",
    ochestvo: "Абдужалиловна",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "6",
    familia: "Базарбаева",
    ism: "Дильсуз",
    ochestvo: "Обид Кизи",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "7",
    familia: "Бахтиярова",
    ism: "Самия",
    ochestvo: "Баходир Киз",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "8",
    familia: "Буронова",
    ism: "Камола",
    ochestvo: "Акрамовна",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "9",
    familia: "Вохиджонов",
    ism: "Абдувахоб",
    ochestvo: "Шерзод угли",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "10",
    familia: "Гафурова",
    ism: "Умида",
    ochestvo: "Масимовна",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
];
