export default [
  {
    _id: "1",
    familia: "Sultanova",
    ism: "Gulbaxor",
    ochestvo: "Yo'zilmagan",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "2",
    familia: "Абдугаффоров",
    ism: "Абдубосит",
    ochestvo: "Абдумалик Угли",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "3",
    familia: "Абдуризаева",
    ism: "Нодира",
    ochestvo: "Мансуровна",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "4",
    familia: "Аитова",
    ism: "Лилия",
    ochestvo: "Рамильевна",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "5",
    familia: "Акрамов",
    ism: "Алибек",
    ochestvo: "Анварович",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "6",
    familia: "Алиппаев",
    ism: "Демир",
    ochestvo: "Мухтарович",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "7",
    familia: "Алишерова",
    ism: "Шахризода",
    ochestvo: "Алишеровна",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "8",
    familia: "Алмасов",
    ism: "Алибек",
    ochestvo: "Сардорович",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "9",
    familia: "Ан",
    ism: "Карина",
    ochestvo: "Олеговна",
    kim: "O‘quvchi",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
  {
    _id: "10",
    familia: "Арипходжаева",
    ism: "Наргиза",
    ochestvo: "Ботир Кизи",
    kim: "Ota-ona",
    foto: "https://image.shutterstock.com/image-vector/dotted-spiral-vortex-royaltyfree-images-600nw-2227567913.jpg",
  },
];
